project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - "papers/**/*.qmd"

website:
  title: "Weekly Paper Sharing"
  site-url: https://kabu1204.github.io/paper-deck/
  navbar:
    left:
      - href: index.qmd
        text: All Papers
  page-footer:
    center: "Source on [GitHub](https://github.com/kabu1204/paper-deck)"

format:
  html:
    theme: flatly
    mainfont: Lora
    css: styles.css
    toc: false
